### ISSUE TITLE
Download results in 404 error

### ISSUE THREAD

**Issue by jjozsi** [eprcstudio/FieldtypeQRCode#1]
Using the classname to install the module doesn't work (not found). The same for using the "Download" button in the ProcessWire module directory.

**Comment by romaincazier** [comment]
Hi,

This was my first time publishing a module on Processwire and I forgot to create a release in the repo. It should be fine now. Please confirm and I'll close the issue.

Thank you for pointing this out.

**Comment by jjozsi** [comment]
It does work now, indeed, thanks!.
